# Generated by Django 4.2.5 on 2023-10-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_dispositivos', models.CharField(max_length=255)),
                ('modelo_dispositivos', models.CharField(max_length=255)),
                ('fecha_dispositivos', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=50)),
                ('usuario_apellido', models.CharField(max_length=50)),
                ('usuario_telefono', models.CharField(max_length=15)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
